name: reviewdog
on: [pull_request]
jobs:
  yamllint:
    name: runner / yamllint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: yamllint
        uses: reviewdog/action-yamllint@v1
        with:
          reporter: github-pr-review # Change reporter.
          yamllint_flags: 'config/'
      - name: Yaml Schema Validator using Yamale
        uses: PaulRitter/yaml-schema-validator@v1
        with:
          schema: endpoint_configuration_schema.yml
          path_pattern: config/*.ya?ml$
